services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./Dockerfile
    rootDir: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
