services:
  - type: web
    name: Credit-Decisioning-App
    env: docker
    dockerfilePath: ./Dockerfile
    rootDir: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 10000




